[masters]
master ansible_host=10.188.157.79
master-2 ansible_host=10.188.157.193
master-3 ansible_host=10.188.157.222

[workers]
worker1 ansible_host=10.188.157.32
worker2 ansible_host=10.188.157.244

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa 
ansible_ssh_common_args='-o StrictHostKeyChecking=no'