apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: imagegalary-test

resources:
  - laravel-service.yaml
  - postgres.yaml           
  - laravel-rollout.yaml    
  - minio.yaml             
  - network-policies.yaml  
  - ingress.yaml           
  - hpa.yaml               