---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: imagegalary:latest 
        resources:
          requests:
            cpu: "200m"   
            memory: "256Mi"
          limits:  
            cpu: "1000m"   
            memory: "2Gi"
        env:
        - name: DB_CONNECTION
          value: "pgsql"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "imagegalary"
        - name: FILESYSTEM_DISK
          value: "s3"
        - name: AWS_USE_PATH_STYLE_ENDPOINT
          value: "true" 
        envFrom:
        - secretRef:
            name: app-secrets
        ports:
        - containerPort: 80