apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-backup-sa
  namespace: imagegalary-test

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minio-backup-role
  namespace: imagegalary-test
rules:
- apiGroups: ["ops.imagegalary.local"]
  resources: ["miniobackups"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-backup-binding
  namespace: imagegalary-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minio-backup-role
subjects:
- kind: ServiceAccount
  name: minio-backup-sa
  namespace: imagegalary-test

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: minio-backup-controller
  namespace: imagegalary-test
spec:
  schedule: "0 3 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: minio-backup-sa

          volumes:
          - name: shared-data
            emptyDir: {}

          initContainers:
          - name: fetch-crd-params
            image: bitnami/kubectl:latest
            volumeMounts:
            - name: shared-data
              mountPath: /shared
            command: 
            - /bin/sh
            - -c
            - |
              # Читаем поля sourceBucket и archiveBucket из твоего CRD app-images-backup
              SOURCE=$(kubectl get miniobackup app-images-backup -n imagegalary-test -o jsonpath='{.spec.sourceBucket}')
              ARCHIVE=$(kubectl get miniobackup app-images-backup -n imagegalary-test -o jsonpath='{.spec.archiveBucket}')
              
              echo "Fetched Source: $SOURCE"
              echo "Fetched Archive: $ARCHIVE"
              
              # Записываем их в файл в общей папке
              echo "export SOURCE_BUCKET=$SOURCE" > /shared/vars.sh
              echo "export ARCHIVE_BUCKET=$ARCHIVE" >> /shared/vars.sh

          containers:
          - name: mc-backup
            image: minio/mc:latest
            volumeMounts:
            - name: shared-data
              mountPath: /shared
            command: 
            - /bin/sh
            - -c
            - |
              source /shared/vars.sh
              
              echo "Starting backup from $SOURCE_BUCKET to $ARCHIVE_BUCKET..."
              
              mc alias set myminio http://minio-service:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
              mc mirror --overwrite myminio/$SOURCE_BUCKET myminio/$ARCHIVE_BUCKET
            env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets 
                  key: AWS_ACCESS_KEY_ID
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets 
                  key: AWS_SECRET_ACCESS_KEY
          restartPolicy: OnFailure