apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: imagegalary-test
spec:
  instances: 2
  storage:
    storageClass: longhorn
    size: 10Gi
  backup:
    barmanObjectStore:
      destinationPath: "s3://pg-backups/" # Бакет в MinIO (создай его заранее)
      endpointURL: "http://minio-service.imagegalary-test.svc.cluster.local:9000"
      s3Credentials:
        accessKeyId:
          name: app-secrets
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: app-secrets
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
  bootstrap:
    initdb:
      database: imagegalary
      owner: appuser