name: Deploy Infrastructure (Terraform)

on:
  push:
    branches:
      - test
      - main
    paths:
      - 'infrastructure/terraform/**'

jobs:
  terraform-apply:
    runs-on: self-hosted
    env:
      TF_VAR_minio_access_key: ${{ secrets.MINIO_ACCESS_KEY }}
      TF_VAR_minio_secret_key: ${{ secrets.MINIO_SECRET_KEY }}
      TF_VAR_rancher_token: ${{ secrets.RANCHER_TOKEN }}
      TF_VAR_keycloak_secret_key: ${{ secrets.KEYCLOAK_SECRET_KEY }}

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/k8s_terraform
          chmod 600 ~/.ssh/k8s_terraform

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # ----- ИНФРАСТРУКТУРА (Helm-релизы) -----
      - name: Terraform Init (Infra)
        working-directory: infrastructure/terraform/infra
        run: terraform init

      - name: Terraform Plan (Infra)
        working-directory: infrastructure/terraform/infra
        run: terraform plan

      - name: Terraform Apply (Infra)
        working-directory: infrastructure/terraform/infra
        run: terraform apply -auto-approve

      # ----- СЕТЕВЫЕ ПОЛИТИКИ -----
      - name: Terraform Init (NetPol)
        working-directory: infrastructure/terraform/netpol
        run: terraform init

      - name: Terraform Plan (NetPol)
        working-directory: infrastructure/terraform/netpol
        run: terraform plan

      - name: Terraform Apply (NetPol)
        working-directory: infrastructure/terraform/netpol
        run: terraform apply -auto-approve